### ISSUE TITLE
Columns should use attribute name, not column-name (as tables do)

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#3]
This bug is acknowledged, and under active investigation.

**Comment by valhuber** [comment]
Fix expected Mon, Jan 24, 2021.

**Comment by thomaxxl** [comment]
Maybe using a mixin like described here works ?https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html

```python
from sqlalchemy.ext.declarative import declared_attr

class BaseModel(SAFRSBase, db.Model):
    __abstract__ = True
    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

```

then, subclass models from `BaseModel` instead of using the multiple inheritance. This might help for #2 too

I like to use tablename to refer to collections and classname to refer to instances.

**Comment by valhuber** [comment]
Version 1.01.01 fixes this for tables; columns are under consideration.
