### ISSUE TITLE
Retrieve Customer Orders failing in Swagger

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#8]
$ ApiLogicServer run

In Swagger, get on Customer OrdersList (http://localhost:5000/#/Customer/RetrieveOrderfromOrderList_0) , observe error:

{
  "errors": [
    {
      "title": "'<' not supported between instances of 'NoneType' and 'str'",
      "detail": "'<' not supported between instances of 'NoneType' and 'str'",
      "code": 500
    }
  ]
}

**Comment by thomaxxl** [comment]
This is because of some of the sort field values are NULL in the db while others are filled in.
`GET /Customer/ALFKI/OrderList` works
`GET /Customer/ALFKI/OrderList?sort=CustomerId,EmployeeId` works
but 
`GET /Customer/ALFKI/OrderList?sort=OrderDate` fails


I've fixed this in the safrs code (https://github.com/thomaxxl/safrs/commit/7b98e214588e2dbbde1ff2b9d5ee6967bc36cd73)

**Comment by valhuber** [comment]
Fixed in 1.4.0, per SAFRS V2.11.1
